### ISSUE TITLE
output of python train_tacotron.py --force_align

### ISSUE THREAD

**Issue by abylouw** [as-ideas/ForwardTacotron#10]
Hi,

Thanks for this work. Can you please explain what the output of ```python train_tacotron.py --force_align``` is? I would like to try training with durations from a forced alignment procedure produced by an ASR model.

**Comment by cschaefer26** [comment]
Hi, the output is a numpy array for each sample with length T containing the duration for each phoneme p_t, which is the number of mel frames for that phoneme. The phonemes for each sample are stored in the text_dict after preprocessing. Do you have an ASR ready for extracting the durations? This is something I will look into soon.

**Comment by abylouw** [comment]
Thank you for the prompt reply. Yes, I have htk based ASR models that I can use for my languages. I will report back once I have made some progress.

**Comment by cschaefer26** [comment]
Cool, keep me posted! Imo there is potential for quality gains with such an approach.
