### ISSUE TITLE
Loss masking bug?

### ISSUE THREAD

**Issue by m-toman** [as-ideas/ForwardTacotron#21]
Hi,

just noticed that the length dimension for the mel spectra when returning from model is 2 as here:
https://github.com/as-ideas/ForwardTacotron/blob/08c67bcbc55b9e2951f59de94de601601e968b7e/models/forward_tacotron.py#L148

And in the loss function the max len is calculated as following: 
https://github.com/as-ideas/ForwardTacotron/blob/08c67bcbc55b9e2951f59de94de601601e968b7e/trainer/common.py#L67
from dim 1.

I never actually tested it with your codebase but with mine I'm getting max_len 80 and therefore a mask with [32, 80] that is then expanded to [32, 80, T].

Sounds wrong on first glance?

**Comment by cschaefer26** [comment]
I just checked and I think you are right, seems like a bug. Luckily it doesnt do much damage as it simply does not mask anything I guess. Check out the PR https://github.com/as-ideas/ForwardTacotron/pull/22  that should fix it. Thx for sharing!°

**Comment by m-toman** [comment]
Should be solved then. Personally with my codebase I didn't see a huge difference either... unfortunately ;)
