### ISSUE TITLE
*.npy files in alg and gta folders for training forward tacotron

### ISSUE THREAD

**Issue by katyamineeva** [as-ideas/ForwardTacotron#3]
Hi!

If I understand everything correctly, it's impossible to run `train_forward.py` without running prior it `train_tacotron.py` with flag `--force_align` set. Otherwise, `train_forward.py` fails:

```
Traceback (most recent call last):
  File "train_forward.py", line 103, in <module>
    trainer.train(model, optimizer)
  File "/mnt/sdb/ForwardTacotron/trainer/forward_trainer.py", line 36, in train
    bs=bs, train_set=train_set, val_set=val_set)
  File "/mnt/sdb/ForwardTacotron/trainer/common.py", line 23, in __init__
    self.val_sample = next(iter(val_set))
...
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/sdb/data/RUSLAN/tiny_version/alg/<some wavname>.npy'
```

Please, add flag `--force_align` to  `train_forward.py` or at least mention this in README.md. And thank you for this repo!

**Comment by cschaefer26** [comment]
Hi, that is correct, first a Tacotron is trained and used for extracting the alignments. The steps are described in the README.md. I now added a sanity check for the for the train_forward.py script that should help.
