### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by blue-fish** [as-ideas/ForwardTacotron#31]
Hi @cschaefer26, I am confused because your repo's license appears to be a MIT license, but also states:
```
Copyright (c) 2020 Axel Springer AI. All rights reserved.
```

Can I use your code in my project? Are redistributions of code allowed?

**Comment by cschaefer26** [comment]
Hi, the license is MIT, so redistribution is warranted as stated. So you can use the code no problems!

**Comment by blue-fish** [comment]
Awesome, thanks for your contributions to open source!
