### ISSUE TITLE
training on custom language

### ISSUE THREAD

**Issue by inferenz-manmohan** [as-ideas/ForwardTacotron#33]
thanks for great work.

Can you guide which part of code to change to work with language other than english. (ex. hindi)?

**Comment by cschaefer26** [comment]
Hi, have a look at the README. Basically you need to change the language and cleaner flags (language = 'hi',. cleaners = 'basic_cleaners') that should do the job.

**Comment by inferenz-manmohan** [comment]
ok thanks for help
