### ISSUE TITLE
Non-attentive Tacotron by Google

### ISSUE THREAD

**Issue by alexdemartos** [as-ideas/ForwardTacotron#34]
Hi, Google just published a model similar to yours. I just thought it might be interesting for you, in case you haven't read it yet :p

https://openreview.net/pdf?id=CGFN_nV1ql

I think it's particularly interesting the Gaussian way they upsample the encoder outputs, and maybe also the positional encoding.

Best regards!

**Comment by cschaefer26** [comment]
Cool, didnt read that yet - looks interesting, thanks!
