### ISSUE TITLE
Transfer learning and tips for internationalization

### ISSUE THREAD

**Issue by oliveiracwb** [as-ideas/ForwardTacotron#4]
**First of all, thanks for this repo**.
Can you talk about transferring learning and/or tips on using it in other languages?
I am training Portuguese with an optimized version of https://github.com/Edresson/TTS-Portuguese-Corpus and I am happy with the results.
I realized that I will have to fix my https://github.com/as-ideas/ForwardTacotron/blob/155c0ba6225e97a8c3a844e810e1a24b4859426e/utils/text/cleaners.py#L13 that are not perfect, although clearly documented.

**Comment by cschaefer26** [comment]
Hi, transfer learning is not really implemented in the TTS model - there is a great repo dealing with it: https://github.com/CorentinJ/Real-Time-Voice-Cloning

As for the cleaners you can probably start out just using the 'basic_cleaners' and see if you need to normalize numbers as well. I have a 'german' branch where I added some german text normalization, if hthat helps anything.

**Comment by oliveiracwb** [comment]
Thank you.
I will see your repository in German.
Since tacatron 2 is capable of transferring learning, I thought it was possible here too.
Big dreams and success!
