### ISSUE TITLE
Permanent Reference for the repository

### ISSUE THREAD

**Issue by yurtmete** [as-ideas/ForwardTacotron#48]
Hi there, 

I also would like to reference Forward Tacotron in a scientific publication. Since there is no paper of your repository, could you also share us the way to reference your work scientifically? 

It was requested here https://github.com/as-ideas/ForwardTacotron/issues/43 but was not revealed publicly.

Thank you in advance

**Comment by cschaefer26** [comment]
Hi yurtmete, you could go with something like this (or similar) for BibTex:

@misc{Schaefer2020,
  author = {Schafer, C.},
  title = {ForwardTacotron},
  year = {2020},
  publisher = {GitHub},
  journal = {GitHub repository},
  howpublished = {\url{https://github.com/as-ideas/ForwardTacotron}},
  commit = {...}
}
