### ISSUE TITLE
Advice on prepping datasets other than LJspeech?

### ISSUE THREAD

**Issue by scripples** [as-ideas/ForwardTacotron#6]
Hi, I'm trying to prep my own dataset to train on the ForwardTacotron model--could you give any insight as to what train_tacotron.py or train_forward.py is expecting in terms of training data organization? Like, the old NVIDIA TT2 repo expects two text files formatted in a certain way and a path to the WAV files in the arguments. Is there something similar for this repo?

**Comment by cschaefer26** [comment]
Hey, just prepare your dataset in the LJSpeech format, if the language differs from English, make sure you set the correct language in the hparams.py file and use tts_cleaner_name=basic_cleaners
```
|- dataset_folder/
|   |- metadata.csv
|   |- wav/
|       |- file1.wav
|       |- ...
```

I updated the README to be clearer on this. Best of luck!

**Comment by scripples** [comment]
Thanks for your help! I'm looking forward to giving it a try.

**Comment by paklau99988** [comment]
Where find list is supported languages?

**Comment by prajwaljpj** [comment]
@paklau99988 you can find the list of languages from [here](https://github.com/espeak-ng/espeak-ng/blob/master/docs/languages.md)
