### ISSUE TITLE
Adding pauses to the input text

### ISSUE THREAD

**Issue by lukacupic** [as-ideas/ForwardTacotron#63]
Hi. I was wondering if there was any way to add (longer) pauses in between sentences of the input text?

I've also seen in some other issues the idea of controling this with a factor, but I was unable to find it in the code. Could you give a few tips on this?

Thanks

**Comment by cschaefer26** [comment]
Hi, the common way to add pauses between sentences is to synthesize each sentence independently and manually add silent wavs in-between:

`one_sec_pause = np.zeros(22050)`

**Comment by lukacupic** [comment]
@cschaefer26 Thanks!
