### ISSUE TITLE
confuse about duration extract

### ISSUE THREAD

**Issue by thanhlong1997** [as-ideas/ForwardTacotron#64]
Hi 
Thank you for great repo. I am trying to implement version for multi speaker since i already have tacotron2 multi speaker for aliment extraction. Bụt when i extract aliment and duration by command `python train_tacotron.py --force_align`, I have confused that , mel_len is len of ground truth mel spectrogram but aliment matrix is relation between input text and predicted mel spectrogram by tacotron. So this mel_len will mismatch to aliment attention matrix. I saw that u use this line to bring attention matrix have the same len to mel_len `path_probs = 1.-att[:mel_len, :]`. And this make me confuse, pls explain why this mel_len not be len of predicted mel spectrogram ?

Thank sir

**Comment by cschaefer26** [comment]
Hi, first of all good luck with the multispeaker implementation, I actually have played around with it (branch multispeaker, very old). Regarding your question, the restriction to mel_len is there in case one wants to do batched inference (to remove the paddings).

**Comment by thanhlong1997** [comment]
Oh. Your code extract aliment from tacotron by pass forward not by inference. That why we need get aliment matrix up to mel_len element for removing the padding value. When I replace your tacotron model, i thought aliment matrix must be extracted by running inference and i get the warning "Sum of durations did not match mel length". Now i know why that happen
Thank you for the explain

**Comment by thanhlong1997** [comment]
Can I let the issues open until i finish the implement ?

Thank sir

**Comment by cschaefer26** [comment]
Surely, keep me updated!

**Comment by thanhlong1997** [comment]
Hi, i am successful implement Forward tacotron multispeaker version. The result sound good. Still we are using pretrained tacotron or with my version is mellotron to extract aliment between character and melspectrogram, but in fastpitch and fastspeech i see they now use [montre](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner) to extract aliment. Have you tried it before ? will it better or worse than using tacotron to extract? I have tried using it in fastpitch but still the result is pool

**Comment by cschaefer26** [comment]
Hi, I tried using the MFA for duration extraction before and I found it to be slightly worse, there was also quite some fiddling involved with mapping the phonemes. It wasn't totally bad though.

**Comment by thanhlong1997** [comment]
thank sir
one more question, now i am using grapheme for encoding text, since i have to work with multilingual data. Will use phoneme is better or not ? in fastpitch too, i saw they using both grapheme and phoneme

**Comment by cschaefer26** [comment]
In my experience phonemes trump graphemes big time because of the bijective nature of phonemes that is easier to learn for the tts model. Result is much more stable pronunciation and prosody. For multilingual data simply phonemize your metafile separately and set use_phonemes=False in the config.

**Comment by thanhlong1997** [comment]
do you think non auto-regressive model like forward tacotron or fast speech2 is not as good  as auto-regressive model like tacotron2 ? when i try bot forward tacotron and fast speech on same dataset, i found that the audio generated is not good as result by tacotron2, even it outperform tacotron2 in speed. I am trying to improve your model and fast speech 2 for comparable to tacotron2 but it seem too hard to do this
