### ISSUE TITLE
does the published weights fit the model?

### ISSUE THREAD

**Issue by katyamineeva** [as-ideas/ForwardTacotron#8]
I'm trying to synthesize using gen_forward.py and pretrained weights and getting an error in WaveRNN initialization:

```Initialising WaveRNN Model...

Traceback (most recent call last):
  File "gen_forward.py", line 94, in <module>
    voc_model.load(voc_load_path)
  File "/mnt/sdb/ForwardTacotron_latest/models/fatchord_version.py", line 420, in load
    self.load_state_dict(torch.load(path, map_location=device), strict=False)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 845, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for WaveRNN:
	size mismatch for fc3.weight: copying a param with shape torch.Size([30, 512]) from checkpoint, the shape in current model is torch.Size([512, 512]).
	size mismatch for fc3.bias: copying a param with shape torch.Size([30]) from checkpoint, the shape in current model is torch.Size([512]).
```
And in ForwardTacotron initialization 

```Initialising Forward TTS Model...

Traceback (most recent call last):
  File "gen_forward.py", line 112, in <module>
    tts_model.load(tts_load_path)
  File "/mnt/sdb/ForwardTacotron_latest/models/forward_tacotron.py", line 195, in load
    self.load_state_dict(state_dict, strict=False)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 845, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ForwardTacotron:
	size mismatch for embedding.weight: copying a param with shape torch.Size([148, 256]) from checkpoint, the shape in current model is torch.Size([127, 256]).
```

Am I  missing something?

**Comment by cschaefer26** [comment]
Hi, the hparams.py changed some time ago. You have to set the - - hp_file flag to the file sitting in the notebook_utils. I'm going to update the Readme on this and copy the hparams.py to the pretrained folder.

**Comment by cschaefer26** [comment]
Update done. Hope it helps!

**Comment by dileepshukla901** [comment]
While trying to finetune the pretrained forward tacotron model, using `train_forward.py`, getting an error

`Traceback (most recent call last):
  File "train_forward.py", line 78, in <module>
    restore_checkpoint(model=model, optim=optimizer,
  File "ForwardTacotron/utils/checkpoints.py", line 27, in restore_checkpoint
    model.load_state_dict(checkpoint['model'])
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1223, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ForwardTacotron:
	size mismatch for pitch_pred.rnn.weight_ih_l0: copying a param with shape torch.Size([192, 256]) from checkpoint, the shape in current model is torch.Size([384, 256]).
	size mismatch for pitch_pred.rnn.weight_hh_l0: copying a param with shape torch.Size([192, 64]) from checkpoint, the shape in current model is torch.Size([384, 128]).
	size mismatch for pitch_pred.rnn.bias_ih_l0: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for pitch_pred.rnn.bias_hh_l0: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for pitch_pred.rnn.weight_ih_l0_reverse: copying a param with shape torch.Size([192, 256]) from checkpoint, the shape in current model is torch.Size([384, 256]).
	size mismatch for pitch_pred.rnn.weight_hh_l0_reverse: copying a param with shape torch.Size([192, 64]) from checkpoint, the shape in current model is torch.Size([384, 128]).
	size mismatch for pitch_pred.rnn.bias_ih_l0_reverse: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for pitch_pred.rnn.bias_hh_l0_reverse: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for pitch_pred.lin.weight: copying a param with shape torch.Size([1, 128]) from checkpoint, the shape in current model is torch.Size([1, 256]).
`

are the provided pretrained model compatible with current code base?

**Comment by cschaefer26** [comment]
Hi, the uploaded model is not really intended for finetuning. Imo the architecture should still work but probably the default params changed. AFAIR I increased the pitch_rnn_dims from 64 to 128 (you could try to set it to 64 again)
